debug: true
build:
  image: node:6
  environment:
  - NODE_ENV=dev
  commands:
   - npm install
   - npm test
   - npm prune --production
   
cache:
  mount:
    - node_modules
    - .git

publish:
  docker:
    image: leankit/drone-docker
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: leankit/cowpoke
    storage_driver: overlay
    when:
      branch: master
