debug: true
build:
  image: node:5
  environment:
  - NODE_ENV=dev
  commands:
   - npm install
   - npm test

cache:
  mount:
    - node_modules
    - .git

publish:
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: leankit/cowpoke
    when:
      branch: poc
