debug: true
build:
  image: node:5
  environment:
  - NODE_ENV=dev
  commands:
   - "npm install buildgoggles@0.2.0-3"
   - "./node_modules/buildgoggles/bin/buildgoggles --releaseOwner=BanditSoftware --releaseBranch=master"
   - "npm install"
   - "npm test"

cache:
  mount:
    - node_modules
    - .git

publish:
  docker:
    image: leankit/drone-docker
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: leankit/cowpoke
    storage_driver: overlay