debug: true
build:
  image: "node:5"
  commands:
    - "npm install buildgoggles@0.2.0-3"
    - "npm test"
    - "./node_modules/buildgoggles/bin/buildgoggles --releaseOwner=Leankit --releaseBranch=master"
  environment:
    - NODE_ENV=dev
cache:
  mount:
    - node_modules
    - .git
publish:
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: leankit/cowpoke
    storage_driver: overlay